VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_IDailyTimeTablePresenter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Application.Interface")
Option Explicit

Public Function CreatePlanViewModel(ByVal ClassHourReadModels As App_ClassHourReadModels, ByVal Totals As App_PeriodTotals, ByVal GradeCount As Long, ByVal PeriodCount As Long) As Pre_TableViewModel
End Function

Public Function CreateExeViewModel(ByVal ClassHourReadModels As App_ClassHourReadModels, ByVal Totals As App_PeriodTotals, ByVal GradeCount As Long, ByVal PeriodCount As Long) As Pre_TableViewModel
End Function

