VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_ClassHourRow"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule EncapsulatePublicField
'@Folder("Application.DTO")
Option Explicit

Public NormDate As Date
Public TypeCode As Long
Public Subject  As String
Public Period   As Long
Public Grade    As Long
Public Value    As Long
