VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_IDailyEnrollmentPresenter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Application.Interface")
Option Explicit

Public Function CreateViewModel(ByVal EnrollmentRMs As App_EnrollmentReadModels, ByVal Totals As App_EnrollmentTotals, ByVal MainStreamRM As App_MainStreamReadModel, ByVal SpecialStreamRMs As App_SpecialStreamReadModels) As Pre_TableViewModel
End Function
