VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_IDailyPeriodPresenter"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Application.Interface")
Option Explicit

Public Function CreateViewModel(ByVal ClassHourReadModels As App_ClassHourReadModels, ByVal MainStreamReadModel As App_MainStreamReadModel) As Variant()
End Function
