VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_IMainView"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Application.Interface")
Option Explicit

Public Sub ShowSuccess(ByVal Message As String)
End Sub

Public Sub NotifyBusinessError(ByVal Message As String)
End Sub

Public Sub NotifySystemError()
End Sub
