VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_SubjectRow"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule MoveFieldCloserToUsage, EncapsulatePublicField
'@Folder("Application.DTO")
Option Explicit

Public Name         As String
Public TargetGrade  As String
Public Mark         As String
