VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_ClassHourReadModel"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule MoveFieldCloserToUsage, EncapsulatePublicField
'@Folder("Infrastructure.DTO")
Option Explicit

Public TypeCode As String
Public Grade    As Long
Public ClassNo  As Long
Public Gender   As String
Public Value    As Long
Public Transfer As String
Public Remarks  As String
