VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "App_EnrollmentFormatterDTO"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule MoveFieldCloserToUsage, EncapsulatePublicField
'@Folder("Application.DTO")
Option Explicit

Public MainKey              As String
Public SpecialKey           As String
Public MaleKey              As String
Public FemaleKey            As String
Public MainGradeCount       As Long
Public MainClassNoCount     As Long
Public SpecialClassNoCount  As Long
