VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICommonCellAddress"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule ProcedureNotUsed
'@Folder("CommonCellAddress")
Option Explicit
Public Function ForAddinName() As String
End Function
Public Function ForAddinVersion() As String
End Function
Public Function ForTopFolderPath() As String
End Function
Public Function ForBootBookName() As String
End Function
Public Function ForBootSheetName() As String
End Function
Public Function ForCurrentYear() As String
End Function
Public Function ForScheduleUpDateAt() As String
End Function
Public Function ForLocalBackupFolderPath() As String
End Function

