VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILeave"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'@Exposed
'@Folder("Form")
Option Explicit
Public Sub Register(ByVal BasisDate As Date, ByVal MsgTitle As String)
End Sub
Public Sub Remove()
End Sub
Public Function DataBody() As Variant()
End Function
Public Function TargetName() As String
End Function
Public Function DisplayName() As String
End Function
Public Function LeaveTypeName() As String
End Function
Public Function FirstDate() As Date
End Function
Public Function LastDate() As Date
End Function

