VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ITable"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule VariableNotUsed, EncapsulatePublicField
'@Folder("Table")
Option Explicit
Public ParentSheet  As Worksheet
Public Sub Delete()
End Sub
Public Sub Add(ByRef DataBody() As Variant)
End Sub
Public Function TargetListObject() As ListObject
End Function
Public Function Exists() As Boolean
End Function

