VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Pre_IViewCallback"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Presentation.Interface")
Option Explicit

Public Sub RenderResult(ByVal Result As App_UseCaseResult)
End Sub

Public Sub LogSystemError(ByVal Error As VBA.ErrObject)
End Sub
