VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Inf_EnrollmentRow"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@IgnoreModule EncapsulatePublicField
'@Folder("Infrastructure.DTO")
Option Explicit

Public NormDate As Date
Public RawID    As String
Public Value    As Long
Public Transfer As String
Public Remarks  As String
